provider:
  ssh_key: Nathan's
  region: San Francisco 1
  image: Ubuntu 12.10 x64 Server
  user: nathan

user: nathan

external_ips:
  - 0.0.0.1
  - 0.0.0.2

load_balancer:
  nginx:
    assets: true
    proxy: haproxy
    bind:
      http: 80
      https: 443
  haproxy:
    algorithm: leastconn
    bind:
      3000: 80
      3001: 81
  rails:
    precompile_assets: true

application:
  nginx:
    proxy: unicorn
    bind:
      http: 80
      https: 81
  rails:
    precomiple_assets: true
    git:
      post_receive: restart_unicorn
    unicorn:
      processes: 6
      bind: 4000

redis:
  redis:
    aof: false
    databases: 2

slave_redis:
  redis:
    aof: true
    appendfsync: everysec
